### ISSUE TITLE
Missing start script - Update Readme

### ISSUE THREAD

**Issue by heikoter** [martijnversluis/ChordFiddle#325]
Am I wrong or does something wrong?
But if I follow the instructions in readme `yarn start` script is missing in `package.json`

btw: really great project! Looking forward to support you

**Comment by martijnversluis** [comment]
Hey @heikoter 

I’m very sorry to have missed your question, for some reason I did not receive a notification. 

You’re not wrong, the README is. With the 2.0 launch I changed the app from React to a vanilla JS version, but you rightly pointed out the docs are not up to date. 

I’ll try to fix the docs as good as I can, and maybe add a development server if necessary.
